
CREATE TABLE [dbo].[FlatRates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Rate] [nvarchar](50) NOT NULL,
	[Amount] [money] NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_FlatRates] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]