CREATE TABLE [dbo].[PostalCodes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodeName] [nvarchar](50) NOT NULL,
	[TaxTypeId] [int] NOT NULL,
 CONSTRAINT [PK_PostalCodes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO